logging:
#  指定日誌輸出級別
  level:
    root: info
    com.joe: debug
  file:
#    path: devlog
    name: devlog/RsetService.log

#    自定義輸出格式
#    console: '%d{HH:mm:ss.SSS}'
#    指定日誌配置文件的位置
#  config: classpath:logbak-test.xml
#    path: devlog
